main: main.o setting.o review.o learn.o set_dictionary.o common.o
	clang ../build/main.o ../build/setting.o ../build/review.o ../build/learn.o ../build/set_dictionary.o ../build/common.o -o ~/Documents/learning_english_words/bin/main -lncursesw -lpanelw

main.o: main.c setting.h common.h review.h learn.h set_dictionary.h
	clang -c main.c -o ../build/main.o

setting.o: setting.c setting.h common.h
	clang -c setting.c -o ../build/setting.o

review.o: review.c review.h common.h
	clang -c review.c -o ../build/review.o

learn.o: learn.c learn.h common.h
	clang -c learn.c -o ../build/learn.o

set_dictionary.o: set_dictionary.c set_dictionary.h common.h
	clang -c set_dictionary.c -o ../build/set_dictionary.o

common.o: common.c common.h
	clang -c common.c -o ../build/common.o
